# Generated by Django 3.0.3 on 2020-02-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBindings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('sid', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('binding_type', models.CharField(max_length=500)),
                ('notification_type', models.CharField(choices=[('Email', 'EMAIL'), ('Error', 'ERROR')], max_length=500)),
            ],
        ),
    ]
