# Generated by Django 3.0.3 on 2020-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_userbindings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbindings',
            name='notification_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notfication_type',
            field=models.CharField(choices=[('notification1', 'NOTIFICATION1'), ('notification2', 'NOTIFICATION2'), ('notification3', 'NOTIFICATION3')], max_length=500),
        ),
    ]
